version: '3.7'

services:
  formywife:
    image: formywife:210617
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: forbaby
    volumes:
      - /home/formywife:/home/formywife
    ports:
      - "8000:8000"
    restart: unless-stopped